In [77]:
import numpy as np
import pyart

In [17]:
r_grid = np.arange(81)*1000.
elev_grid_1 = np.arange(5.)
elev_grid_2 = np.arange(5.)+175.
el_grid = np.concatenate((elev_grid_1,elev_grid_2),axis=0)
el_grid_r = el_grid[::-1]

In [18]:
print(elev_grid_1)
print(elev_grid_2)
print(el_grid)
print(el_grid_r)

[0. 1. 2. 3. 4.]
[175. 176. 177. 178. 179.]
[  0.   1.   2.   3.   4. 175. 176. 177. 178. 179.]
[179. 178. 177. 176. 175.   4.   3.   2.   1.   0.]


In [19]:
el_grd = np.concatenate((el_grid,el_grid_r),axis=0)

In [20]:
el_grd.shape

(20,)

In [21]:
elev_grid = np.concatenate((el_grd,el_grd,el_grd),axis=0)

In [22]:
elev_grid.shape

(60,)

In [23]:
print(elev_grid)

[  0.   1.   2.   3.   4. 175. 176. 177. 178. 179. 179. 178. 177. 176.
 175.   4.   3.   2.   1.   0.   0.   1.   2.   3.   4. 175. 176. 177.
 178. 179. 179. 178. 177. 176. 175.   4.   3.   2.   1.   0.   0.   1.
   2.   3.   4. 175. 176. 177. 178. 179. 179. 178. 177. 176. 175.   4.
   3.   2.   1.   0.]


In [51]:
filename = '/run/media/hunzinger/WININSTALL/csapr2-data/corcsaprM1.00.20181018.152556.raw.cor-hsrhi-cacti-b_CSAPR2_20181018152556_00.h5'
radar = pyart.aux_io.read_gamic(filename, file_field_names=True) 

r_start_idx = 0
r_stop_idx = np.where(radar.range['data'] > 80000.)[0][0]
    
elev = radar.elevation['data']
elev_mask =  np.logical_or(np.abs(elev) < 5., elev > 175.)

r = radar.range['data'][r_start_idx:r_stop_idx]
theta = radar.azimuth['data'][elev_mask]
zh = radar.fields['Zh']['data'][elev_mask,r_start_idx:r_stop_idx]
elev = elev[elev_mask]

r_grid = np.arange(81)*1000.
theta_values = np.arange(6.)*30
elev_grid_1 = np.arange(5.)
elev_grid_2 = np.arange(5.)+175.
el_grid = np.concatenate((elev_grid_1,elev_grid_2),axis=0)
el_grid_r = el_grid[::-1]
el = np.concatenate((el_grid,el_grid_r),axis=0)
elev_grid = np.concatenate((el,el,el),axis=0)

r_m, theta_m = np.meshgrid(r,theta)
r_m, elev_m = np.meshgrid(r,elev)
r_matrix, elev_matrix = np.meshgrid(r_grid,elev_grid)
clutter_flag_h = np.zeros((r_matrix.shape))

In [52]:
print(clutter_flag_h.shape)
print(elev_grid.shape)
print(elev.shape)
print(zh.shape)
print(theta.shape)
print(r_m.shape)
theta_m

(60, 81)
(60,)
(111,)
(111, 801)
(111,)
(111, 801)


array([[359.97803, 359.97803, 359.97803, ..., 359.97803, 359.97803,
        359.97803],
       [359.97803, 359.97803, 359.97803, ..., 359.97803, 359.97803,
        359.97803],
       [359.97803, 359.97803, 359.97803, ..., 359.97803, 359.97803,
        359.97803],
       ...,
       [149.98535, 149.98535, 149.98535, ..., 149.98535, 149.98535,
        149.98535],
       [149.98535, 149.98535, 149.98535, ..., 149.98535, 149.98535,
        149.98535],
       [149.98535, 149.98535, 149.98535, ..., 149.98535, 149.98535,
        149.98535]], dtype=float32)

In [76]:
zh.shape
ELEV_LIST = [[] for i in range(0,len(elev_grid))]
len(ELEV_LIST)

# Create mask for each azimuithal angle 
theta_0_mask = np.logical_or(np.logical_and(theta >= 0., theta < 2.), theta > 358.)
theta_30_mask = np.logical_and(theta > 29., theta < 31.)
theta_60_mask = np.logical_and(theta > 59., theta < 61.)
theta_90_mask = np.logical_and(theta > 89., theta < 91.)
theta_120_mask = np.logical_and(theta > 119., theta < 121.)
theta_150_mask = np.logical_and(theta > 149., theta < 151.)

theta_mask = [theta_0_mask,theta_30_mask,theta_60_mask,theta_90_mask,theta_120_mask,theta_150_mask]

elev_0 = elev[theta_0_mask]
elev_30 = elev[theta_30_mask]
elev_60 = elev[theta_60_mask]
elev_90 = elev[theta_90_mask]
elev_120 = elev[theta_120_mask]
elev_150 = elev[theta_150_mask]


print(elev_0)
print(elev_30)
print(elev_60)
print(elev_90)
print(elev_120)
print(elev_150)

print(elev_0)

zh_0 = zh[theta_0_mask]
zh_30 = zh[theta_30_mask]
zh_60 = zh[theta_60_mask]
zh_90 = zh[theta_90_mask]
zh_120 = zh[theta_120_mask]
zh_150 = zh[theta_150_mask]

print(zh_0.shape)


#for i in range(0,len(elev_0)):
#    for j in range(0,len(r)):
#        if zh_0[i,j] >= z_thresh:
            

#len(elev)

zh_0_idx = np.where(zh_0 >= z_thresh)
zh_30_idx = np.where(zh_30 >= z_thresh)
zh_60_idx = np.where(zh_60 >= z_thresh)
zh_90_idx = np.where(zh_90 >= z_thresh)
zh_120_idx = np.where(zh_120 >= z_thresh)
zh_150_idx = np.where(zh_150 >= z_thresh)

#print(zh_0_idx)
#print(zh_30_idx)
#print(zh_60_idx)
#print(zh_90_idx)
#print(zh_120_idx)
#print(zh_150_idx)




clutter_flag_h_0 = np.zeros((10,81))
clutter_flag_h_30 = np.zeros((10,81))
clutter_flag_h_60 = np.zeros((10,81))
clutter_flag_h_90 = np.zeros((10,81))
clutter_flag_h_120 = np.zeros((10,81))
clutter_flag_h_150 = np.zeros((10,81))

z_thresh = 45. #dBZ

#print(zh_0.shape, zh_30.shape, zh_60.shape)
#for i in range(0,len(elev)):
#print(elev[theta_0_mask])
#print(elev[theta_60_mask])
#print(elev[theta_120_mask])
#print('                  ')
##print(elev[theta_30_mask])
#print(elev[theta_90_mask])
#print(elev[theta_150_mask])
    
#print(theta_mask)

# For each azimuth, flag for clutter and indicate the Zh gates that fall within clutter flag box
# THETA = 0 DEG
#for i in range(0,len(elev_grid)):
#    for j in range(0,len(r_grid)):

#for i in theta_values: # 0,30,60,90,120,150
#    for j in range(0,len(ELEV_LIST)): #0 - 59
        
        
#for i in theta_values:
#x = [[] for i in range(10)]
#print(x)

[  0.7690429   1.2634279   1.7797852   2.2851562   2.7905273   3.3068848
   3.8012698   4.2736816   4.7570806 175.2649    175.78125   176.2976
 176.80298   177.28639   177.76978   178.27515   178.7915    179.30786  ]
[179.73633    179.23096    178.70361    178.18726    177.71484
 177.23145    176.7151     176.19873    175.70435    175.20996
   4.7351074    4.2187505    3.7023928    3.1970215    2.6916504
   2.1972654    1.7028807    1.2194824    0.73608404]
[  0.7800293   1.2963867   1.8017578   2.27417     2.7575684   3.2629395
   3.7902834   4.295655    4.7790523 175.28687   175.77026   176.25366
 176.75905   177.2644    177.76978   178.27515   178.7915    179.30786  ]
[179.71436   179.21997   178.7146    178.20923   177.70386   177.22046
 176.72607   176.20972   175.72632   175.23193     4.7351074   4.229736
   3.713379    3.208008    2.713623    2.219238    1.7248536   1.208496
   0.7141114]
[  0.7800293   1.2963867   1.8017578   2.2961428   2.779541    3.2629395
   3.7792969   4.2

In [47]:
zh_idx = np.where(zh >= z_thresh)
print(zh_idx)
print(zh[zh_idx])
print(elev_m[zh_idx])
print(r_m[zh_idx])

print(zh_idx[:,0])
#clutter_flag_h[zh_thresh_mask] == 1.
#print(clutter_flag_h[19,56])

(array([19, 56]), array([23, 21]))
[45.26143264770508 56.203983306884766]
[179.23096 179.21997]
[2300. 2100.]


TypeError: tuple indices must be integers or slices, not tuple

In [30]:
print(elev)

[  0.7690429    1.2634279    1.7797852    2.2851562    2.7905273
   3.3068848    3.8012698    4.2736816    4.7570806  175.2649
 175.78125    176.2976     176.80298    177.28639    177.76978
 178.27515    178.7915     179.30786    179.73633    179.23096
 178.70361    178.18726    177.71484    177.23145    176.7151
 176.19873    175.70435    175.20996      4.7351074    4.2187505
   3.7023928    3.1970215    2.6916504    2.1972654    1.7028807
   1.2194824    0.73608404   0.7800293    1.2963867    1.8017578
   2.27417      2.7575684    3.2629395    3.7902834    4.295655
   4.7790523  175.28687    175.77026    176.25366    176.75905
 177.2644     177.76978    178.27515    178.7915     179.30786
 179.71436    179.21997    178.7146     178.20923    177.70386
 177.22046    176.72607    176.20972    175.72632    175.23193
   4.7351074    4.229736     3.713379     3.208008     2.713623
   2.219238     1.7248536    1.208496     0.7141114    0.7800293
   1.2963867    1.8017578    2.2961428    2.7

In [31]:
print(theta)

[359.97803  359.97803  359.97803  359.97803  359.97803  359.97803
 359.97803  359.97803  359.97803    0.         0.         0.
   0.         0.         0.         0.         0.         0.
  30.036621  30.036621  30.025639  30.014648  30.014648  30.014648
  30.014648  30.014648  30.014648  30.014648  29.970703  29.970703
  29.970703  29.970703  29.970703  29.970703  29.970703  29.970703
  29.970703  60.029297  60.018314  60.007324  60.007324  60.007324
  60.007324  60.007324  60.007324  60.007324  59.98535   59.98535
  59.98535   59.98535   59.98535   59.98535   59.98535   59.98535
  59.98535   90.03296   90.02197   90.02197   90.02197   90.02197
  90.02197   90.01099   90.        90.        90.        89.97803
  89.97803   89.97803   89.97803   89.97803   89.97803   89.97803
  89.97803   89.97803  120.03661  120.03661  120.03661  120.025635
 120.01465  120.01465  120.01465  120.01465  120.01465  119.99268
 119.99268  119.99268  119.99268  119.99268  119.99268  119.99268
 119.99268  119